/**@typedef {Object} ConstructionItem
*@property {string} id
*@property {string} label
*@type {Object.<string, ConstructionItem[]>}
*/

/**
 * @type {Object.<string, ConstructionItem[]>}
 */

export const INSPECTORS = [
    {id: 1, label: "Asheeqa Emamdien"},
    {id: 2, label: "Hessen Petrus"},
    {id: 3, label: "Kevin Walter"},
    {id: 4, label: "Ndeshihafela Neliwa"},
    {id: 5, label: "Wilhelmina Ngulu"} 
];

export const SIZE_CATEGORY = [
    {id: 1, label: "Small bridge (Shorter than 20m)"},
    {id: 2, label: "Medium bridge (From 20m but shorter than 50m)"},
    {id: 3, label: "Large bridge (50m but shorter than 100m)"},
    {id: 4, label: "Very large bridge (longer than 100m)"}
];

export const BRIDGE_TYPE = [
    {id: 1, label: "Simply supported"},
    {id: 2, label: "Continuous"},
    {id: 3, label: "Cantilever with drop in spans"},
    {id: 4, label: "Frame"},
    {id: 5, label: "Arch"},
    {id: 6, label: "Cable"},
    {id: 7, label: "Truss"},
    {id: 8, label: "Plate girder"},
    {id: 9, label: "Cellular"},
    {id: 10, label: "Continous and simply supported"},
    {id: 11, label: "Corrugated metal arch"},
    {id: 12, label: "Multi-continuous"},
    {id: 13, label: "Integral bridge"},
    {id: 14, label: "Continuous with drop-in span"},
    {id: 15, label: "NA"},
    {id: 16, label: "Unknown"},
    {id: 17, label: "Other"}
];

export const FEATURE_CROSSED = [
    {id: 1, label: "Road"},
    {id: 2, label: "River"},
    {id: 3, label: "Railway"},
    {id: 4, label: "Canal"},
    {id: 5, label: "Pedestrian"},
    {id: 6, label: "Habitaiton"},
    {id: 7, label: "Valley"},
    {id: 8, label: "Railway"},
    {id: 9, label: "Utility"},
    {id: 10, label: "Open veld/ Farm land"},
    {id: 11, label: "Conveyor Belt"},
    {id: 12, label: "Agicultural overpass"},
    {id: 13, label: "Agicultural underpass"},
    {id: 14, label: "Services"},
    {id: 15, label: "NA"},
    {id: 16, label: "Unknown"},
    {id: 18, label: "None"},
    {id: 17, label: "Other"}
];

export const STRUC_ORIENTATION = [
    {id: 1, label: "North/South"},
    {id: 2, label: "East/West"},
    {id: 3, label: "Northeast/Southwest"},
    {id: 4, label: "Northwest/Southeast"}
];

export const RIVER_FLOW_DIRECTION = [
    {id: 1, label: "North"},
    {id: 2, label: "East"},
    {id: 3, label: "West"},
    {id: 4, label: "South"},
];

export const ROAD_OVERUNDER = [
    {id: 1, label: "Over only"},
    {id: 2, label: "Under only"},
    {id: 3, label: "Adjacent"}
];

export const HORIZONTAL_ALIGNMENT = [
    {id: 1, label: "Straight"},
    {id: 2, label: "Curved"},
    {id: 3, label: "Compound Curve"},
    {id: 4, label: "Skew"},
    {id: 5, label: "Other"},
    {id: 6, label: "NA"},
    {id: 7, label: "Spiral"},
    {id: 8, label: "Parellel"},
    {id: 9, label: "Transition Curves"},
    {id: 10, label: "Reverse Curves"},
    {id: 11, label: "Super-elevation"},
];

export const VERTICAL_ALIGNMNT = [
    {id: 1, label: "Flat or Level Bridge"},
    {id: 2, label: "Sag Curve"},
    {id: 3, label: "Crest Curve"},
    {id: 4, label: "Not Sure"},
    {id: 5, label: "Other"},
    {id: 6, label: "NA"},
];

export const CONSTRUCTION_ELEMENTS = {
  "ApproachEmbankment": [
    { id: "01.116", label: "Repair concrete sidedrain/gutter/downchute" },
    { id: "01.155", label: "Earth backfill" },
    { id: "01.156", label: "Gabion (mattresses and boxes)" },
    { id: "01.157", label: "Mass concrete backfill" },
    { id: "01.158", label: "Rock backfill" },
    { id: "01.201", label: "Clean downchutes/sidedrains" },
    { id: "01.357", label: "Replace kerbs or berms" },
    { id: "01.358", label: "Replace cover slabs and lids" },
    { id: "01.359", label: "Replace sidedrain/gutter/downchutes" },
    { id: "01.362", label: "Replace inlet/outlet structures" },
    { id: "01.363", label: "Install kerbs or berms" },
    { id: "01.402", label: "Clear bush" },
    { id: "01.404", label: "Remove trees (girth < 500 mm)" },
    { id: "01.405", label: "Remove trees (girth > 500 mm)" },
    { id: "01.504", label: "Repair settlement (asphalt fill)" },
    { id: "01.953", label: "Ad-hoc item (describe under Remarks)" }
  ],
  "Guardrail": [
    { id: "02.451", label: "Attach guardrail to endblock" },
    { id: "02.452", label: "Cut bolts for pedestrian safety" },
    { id: "02.455", label: "New guardrail (single and double)" },
    { id: "02.463", label: "Repair guardrail (realign, bolt replacement, etc.)" },
    { id: "02.466", label: "Replace bolts and washers" },
    { id: "02.467", label: "Replace posts (steel or timber)" },
    { id: "02.469", label: "Reverse laps in guardrails" },
    { id: "02.953", label: "Ad-hoc item (describe under Remarks)" }
  ],
  "Waterway": [
    { id: "03.151", label: "Backfill scour damage (earth)" },
    { id: "03.152", label: "Backfill scour damage (mass concrete)" },
    { id: "03.153", label: "Backfill scour damage (rock)" },
    { id: "03.156", label: "Gabion (mattresses and boxes)" },
    { id: "03.207", label: "Clear debris" },
    { id: "03.209", label: "Clear siltation" },
    { id: "03.404", label: "Remove trees (girth < 500 mm)" },
    { id: "03.405", label: "Remove trees (girth > 500 mm)" },
    { id: "03.953", label: "Ad-hoc item (describe under Remarks)" }
  ],
  "ApproachEmbankmentProtect": [
    { id: "04.155", label: "Earth backfill" },
    { id: "04.156", label: "Gabion (mattresses and boxes)" },
    { id: "04.157", label: "Mass concrete backfill" },
    { id: "04.158", label: "Rock backfill" },
    { id: "04.159", label: "Stone pitching" },
    { id: "04.160", label: "Interlocking blocks" },
    { id: "04.401", label: "Apply weed killer/ant poison and remove growth" },
    { id: "04.403", label: "Grassing" },
    { id: "04.953", label: "Ad-hoc item (describe under Remarks)" }
  ],
  "AbutmentsFoundations": [
    { id: "05.101", label: "Apply protective coating" },
    { id: "05.102", label: "Apply silanes" },
    { id: "05.106", label: "Construct earth berms for access" },
    { id: "05.108", label: "Cut back reinforcement (tie rods) and make good" },
    { id: "05.118", label: "Repair spall (including honeycombing)" },
    { id: "05.120", label: "Seal cracks" },
    { id: "05.155", label: "Earth backfill" },
    { id: "05.156", label: "Gabion (mattresses and boxes)" },
    { id: "05.157", label: "Mass concrete backfill" },
    { id: "05.161", label: "Underpinning (describe under Remarks)" },
    { id: "05.953", label: "Ad-hoc item (describe under Remarks)" }
  ],
  "Abutments": [
    { id: "06.101", label: "Apply protective coating" },
    { id: "06.102", label: "Apply silanes" },
    { id: "06.103", label: "Clean concrete surface" },
    { id: "06.104", label: "Concrete (reinforced)" },
    { id: "06.105", label: "Concrete (mass)" },
    { id: "06.108", label: "Cut back reinforcement (tie rods) and make good" },
    { id: "06.114", label: "Reconstruct backwall (re-instate gap)" },
    { id: "06.115", label: "Repair anchor heads" },
    { id: "06.118", label: "Repair spall (including honeycombing)" },
    { id: "06.120", label: "Seal cracks" },
    { id: "06.122", label: "Stabilise wall with ground/rock anchors" },
    { id: "06.154", label: "Construct masonry wall" },
    { id: "06.202", label: "Clean drainage" },
    { id: "06.207", label: "Clear debris" },
    { id: "06.309", label: "Reinstate expansion gap" },
    { id: "06.311", label: "Remove/repair cladding/bearing protection plates" },
    { id: "06.314", label: "Replace joint sealant" },
    { id: "06.355", label: "Repair weep holes" },
    { id: "06.618", label: "Service and repair gully doors/manholes" },
    { id: "06.653", label: "Access-using scaffold (> 10 m)" },
    { id: "06.654", label: "Access-using scaffold (< 10 m)" },
    { id: "06.702", label: "Traffic accommodation-Low (< 10 000 vpd)" },
    { id: "06.703", label: "Traffic accommodation-Medium (10 000 - 40 000 vpd)" },
    { id: "06.704", label: "Traffic accommodation-High (> 40 000 vpd)" },
    { id: "06.953", label: "Ad-hoc item (describe under Remarks)" }
  ],
  "WingRetainingWalls": [
    { id: "07.101", label: "Apply protective coating" },
    { id: "07.102", label: "Apply silanes" },
    { id: "07.103", label: "Clean concrete surface" },
    { id: "07.105", label: "Concrete (mass)" },
    { id: "07.108", label: "Cut back reinforcement (tie rods) and make good" },
    { id: "07.118", label: "Repair spall (including honeycombing)" },
    { id: "07.120", label: "Seal cracks" },
    { id: "07.122", label: "Stabilise wall with ground/rock anchors" },
    { id: "07.155", label: "Earth backfill" },
    { id: "07.156", label: "Gabion (mattresses and boxes)" },
    { id: "07.157", label: "Mass concrete backfill" },
    { id: "07.158", label: "Rock backfill" },
    { id: "07.161", label: "Underpinning (describe under Remarks)" },
    { id: "07.207", label: "Clear debris" },
    { id: "07.309", label: "Reinstate expansion gap" },
    { id: "07.314", label: "Replace joint sealant" },
    { id: "07.355", label: "Repair weep holes" },
    { id: "07.607", label: "Monitor (movements, rotations, etc.) (5 year period)" },
    { id: "07.653", label: "Access-using scaffold (> 10 m)" },
    { id: "07.654", label: "Access-using scaffold (< 10 m)" },
    { id: "07.702", label: "Traffic accommodation-Low (< 10 000 vpd)" },
    { id: "07.703", label: "Traffic accommodation-Medium (10 000 - 40 000 vpd)" },
    { id: "07.704", label: "Traffic accommodation-High (> 40 000 vpd)" },
    { id: "07.953", label: "Ad-hoc item (describe under Remarks)" }
  ],
  "Surfacing": [
    { id: "08.117", label: "Repair concrete topping" },
    { id: "08.207", label: "Clear debris" },
    { id: "08.209", label: "Clear siltation" },
    { id: "08.501", label: "Crack seal (asphalt)" },
    { id: "08.502", label: "Resurface or patch" },
    { id: "08.505", label: "Shape surfacing at scuppers" },
    { id: "08.702", label: "Traffic accommodation-Low (< 10 000 vpd)" },
    { id: "08.703", label: "Traffic accommodation-Medium (10 000 - 40 000 vpd)" },
    { id: "08.704", label: "Traffic accommodation-High (> 40 000 vpd)" }
  ],
  "SuperstructureDrainage": [
    { id: "09.206", label: "Clear channel" },
    { id: "09.208", label: "Clear scuppers" },
    { id: "09.351", label: "Construct new scuppers" },
    { id: "09.353", label: "Extend scupper below deck soffit" },
    { id: "09.354", label: "Repair scuppers" },
    { id: "09.361", label: "Replace grid inlet" },
    { id: "09.365", label: "Seal leaking pipes" },
    { id: "09.653", label: "Access-using scaffold (> 10 m)" },
    { id: "09.654", label: "Access-using scaffold (< 10 m)" },
    { id: "09.702", label: "Traffic accommodation-Low (< 10 000 vpd)" },
    { id: "09.703", label: "Traffic accommodation-Medium (10 000 - 40 000 vpd)" },
    { id: "09.704", label: "Traffic accommodation-High (> 40 000 vpd)" },
    { id: "09.953", label: "Ad-hoc item (describe under Remarks)" }
  ],
  "KerbsSidewalks": [
    { id: "10.101", label: "Apply protective coating" },
    { id: "10.102", label: "Apply silanes" },
    { id: "10.118", label: "Repair spall (including honeycombing)" },
    { id: "10.120", label: "Seal cracks" },
    { id: "10.207", label: "Clear debris" },
    { id: "10.314", label: "Replace joint sealant" },
    { id: "10.357", label: "Replace kerbs or berms" },
    { id: "10.363", label: "Install kerbs or berms" },
    { id: "10.366", label: "Install/replace concrete channel" },
    { id: "10.568", label: "Replace service duct cover" },
    { id: "10.609", label: "Provide sidewalk" },
    { id: "10.614", label: "Repair sidewalk surface (blocks, screed etc.)" },
    { id: "10.702", label: "Traffic accommodation-Low (< 10 000 vpd)" },
    { id: "10.703", label: "Traffic accommodation-Medium (10 000 - 40 000 vpd)" },
    { id: "10.704", label: "Traffic accommodation-High (> 40 000 vpd)" },
    { id: "10.953", label: "Ad-hoc item (describe under Remarks)" }
  ],
  "Parapet": [
    { id: "11.101", label: "Apply protective coating" },
    { id: "11.103", label: "Clean concrete surface" },
    { id: "11.104", label: "Concrete (reinforced)" },
    { id: "11.113", label: "Concrete (precast)" },
    { id: "11.118", label: "Repair spall (including honeycombing)" },
    { id: "11.120", label: "Seal cracks" },
    { id: "11.309", label: "Reinstate expansion gap" },
    { id: "11.314", label: "Replace joint sealant" },
    { id: "11.453", label: "Install full height pedestrian balustrade" },
    { id: "11.454", label: "New endblocks" },
    { id: "11.456", label: "New pedestrian parapet" },
    { id: "11.457", label: "New traffic barrier (Concrete F-Shape/NJ)" },
    { id: "11.458", label: "New/repair steel railing" },
    { id: "11.459", label: "Paint steel rails" },
    { id: "11.462", label: "Realign handrails" },
    { id: "11.464", label: "Repair/replace guardrail fixings" },
    { id: "11.465", label: "Repair/replace handrail posts" },
    { id: "11.569", label: "Replace service duct cover" },
    { id: "11.651", label: "Access-using hanging basket for outer surface" },
    { id: "11.702", label: "Traffic accommodation-Low (< 10 000 vpd)" },
    { id: "11.703", label: "Traffic accommodation-Medium (10 000 - 40 000 vpd)" },
    { id: "11.704", label: "Traffic accommodation-High (> 40 000 vpd)" },
    { id: "11.953", label: "Ad-hoc item (describe under Remarks)" }
  ],
  "PierProtectionWorks": [
    { id: "12.156", label: "Gabion (mattresses and boxes)" },
    { id: "12.157", label: "Mass concrete backfill" },
    { id: "12.158", label: "Rock backfill" },
    { id: "12.460", label: "Provide guardrail protection" },
    { id: "12.461", label: "Provide F-shape NJ barrier protection" },
    { id: "12.702", label: "Traffic accommodation-Low (< 10 000 vpd)" },
    { id: "12.703", label: "Traffic accommodation-Medium (10 000 - 40 000 vpd)" },
    { id: "12.704", label: "Traffic accommodation-High (> 40 000 vpd)" }
  ],
  "PierFoundations": [
    { id: "13.101", label: "Apply protective coating" },
    { id: "13.102", label: "Apply silanes" },
    { id: "13.104", label: "Concrete (reinforced)" },
    { id: "13.105", label: "Concrete (mass)" },
    { id: "13.106", label: "Construct earth berms for access" },
    { id: "13.118", label: "Repair spall (including honeycombing)" },
    { id: "13.120", label: "Seal cracks" },
    { id: "13.155", label: "Earth backfill" },
    { id: "13.156", label: "Gabion (mattresses and boxes)" },
    { id: "13.157", label: "Mass concrete backfill" },
    { id: "13.158", label: "Rock backfill" },
    { id: "13.161", label: "Underpinning (describe under Remarks)" },
    { id: "13.702", label: "Traffic accommodation-Low (< 10 000 vpd)" },
    { id: "13.703", label: "Traffic accommodation-Medium (10 000 - 40 000 vpd)" },
    { id: "13.704", label: "Traffic accommodation-High (> 40 000 vpd)" },
    { id: "13.953", label: "Ad-hoc item (describe under Remarks)" }
  ],
  "PiersColumns": [
    { id: "14.101", label: "Apply protective coating" },
    { id: "14.102", label: "Apply silanes" },
    { id: "14.103", label: "Clean concrete surface" },
    { id: "14.104", label: "Concrete (reinforced)" },
    { id: "14.108", label: "Cut back reinforcement (tie rods) and make good" },
    { id: "14.118", label: "Repair spall (including honeycombing)" },
    { id: "14.120", label: "Seal cracks" },
    { id: "14.207", label: "Clear debris" },
    { id: "14.310", label: "Remove cladding - bearing plates" },
    { id: "14.653", label: "Access-using scaffold (> 10 m)" },
    { id: "14.654", label: "Access-using scaffold (< 10 m)" },
    { id: "14.702", label: "Traffic accommodation-Low (< 10 000 vpd)" },
    { id: "14.703", label: "Traffic accommodation-Medium (10 000 - 40 000 vpd)" },
    { id: "14.704", label: "Traffic accommodation-High (> 40 000 vpd)" }
  ],
  "Bearings": [
    { id: "15.251", label: "Jacking - complicated (provide jack support work)" },
    { id: "15.252", label: "Jacking - simple (flat jacks)" },
    { id: "15.253", label: "Refurbish (corrosion protection, anchor bolts, etc.)" },
    { id: "15.254", label: "Repair bearing plinth" },
    { id: "15.255", label: "Replace - elastomeric" },
    { id: "15.256", label: "Replace - mechanical" },
    { id: "15.257", label: "Re-seat" },
    { id: "15.258", label: "Service bearing (clear obstructions, etc.)" },
    { id: "15.653", label: "Access-using scaffold (> 10 m)" },
    { id: "15.654", label: "Access-using scaffold (< 10 m)" },
    { id: "15.702", label: "Traffic accommodation-Low (< 10 000 vpd)" },
    { id: "15.703", label: "Traffic accommodation-Medium (10 000 - 40 000 vpd)" },
    { id: "15.704", label: "Traffic accommodation-High (> 40 000 vpd)" },
    { id: "15.953", label: "Ad-hoc item (describe under Remarks)" }
  ],
  "SupportedDrainage": [
    { id: "16.205", label: "Clear blocked drainage" },
    { id: "16.360", label: "Replace drainage" },
    { id: "16.953", label: "Ad-hoc item (describe under Remarks)" }
  ],
  "ExpansionJoints": [
    { id: "17.203", label: "Clean joint of loose material" },
    { id: "17.301", label: "Install silicon/bituminous seal" },
    { id: "17.302", label: "Joint cover plates (replace and refit)" },
    { id: "17.304", label: "New 40mm claw" },
    { id: "17.305", label: "New 80mm claw" },
    { id: "17.306", label: "New asphalt plug joint" },
    { id: "17.307", label: "New multi element joint" },
    { id: "17.308", label: "Refurbish (paint, etc.) metal claw/rail" },
    { id: "17.312", label: "Repair concrete at joint up-turns" },
    { id: "17.313", label: "Repair concrete nosing" },
    { id: "17.315", label: "Replace glands of claw joint" },
    { id: "17.316", label: "Replace pressfit seal with silicone" },
    { id: "17.317", label: "Service multi-element joint" },
    { id: "17.702", label: "Traffic accommodation-Low (< 10 000 vpd)" },
    { id: "17.703", label: "Traffic accommodation-Medium (10 000 - 40 000 vpd)" },
    { id: "17.704", label: "Traffic accommodation-High (> 40 000 vpd)" },
    { id: "17.953", label: "Ad-hoc item (describe under Remarks)" }
  ],
  "LongitudinalMembers": [
    { id: "18.101", label: "Apply protective coating" },
    { id: "18.102", label: "Apply silanes" },
    { id: "18.103", label: "Clean concrete surface" },
    { id: "18.104", label: "Concrete (reinforced)" },
    { id: "18.108", label: "Cut back reinforcement (tie rods) and make good" },
    { id: "18.110", label: "Jacking - complicated (provide jack support work)" },
    { id: "18.111", label: "Jacking - simple (flat jacks)" },
    { id: "18.118", label: "Repair spall (including honeycombing)" },
    { id: "18.120", label: "Seal cracks" },
    { id: "18.123", label: "Strengthening (using plates, carbon fibre, etc.)" },
    { id: "18.352", label: "Drill drainage holes" },
    { id: "18.520", label: "Cable anchorage refurbishment for cables up to 100 mm diameter" },
    { id: "18.521", label: "Cable anchorage refurbishment for cables 100 mm to 200 mm diameter" },
    { id: "18.522", label: "Cable anchorage refurbishment for cables greater than 200 mm diameter" },
    { id: "18.523", label: "Cable replacement up to 100 mm diameter" },
    { id: "18.524", label: "Cable replacement 100 mm to 200 mm diameter" },
    { id: "18.525", label: "Cable replacement greater than 200 mm diameter" },
    { id: "18.526", label: "Access to pylon head for repair (crane or other means)" },
    { id: "18.527", label: "Install vandalism tubes to cables" },
    { id: "18.528", label: "Additional (corrosion) protection for cables (painting, wrapping or sheathing a cable)" },
    { id: "18.553", label: "Corrosion protection to steel cables" },
    { id: "18.576", label: "Structural steel - re-torque bolts" },
    { id: "18.653", label: "Access-using scaffold (> 10 m)" },
    { id: "18.654", label: "Access-using scaffold (< 10 m)" },
    { id: "18.702", label: "Traffic accommodation-Low (< 10 000 vpd)" },
    { id: "18.703", label: "Traffic accommodation-Medium (10 000 - 40 000 vpd)" },
    { id: "18.953", label: "Ad-hoc item (describe under Remarks)" }
  ],
  "TransverseMembers": [
    { id: "19.101", label: "Apply protective coating" },
    { id: "19.102", label: "Apply silanes" },
    { id: "19.103", label: "Clean concrete surface" },
    { id: "19.104", label: "Concrete (reinforced)" },
    { id: "19.108", label: "Cut back reinforcement (tie rods) and make good" },
    { id: "19.110", label: "Jacking - complicated (provide jack support work)" },
    { id: "19.111", label: "Jacking - simple (flat jacks)" },
    { id: "19.118", label: "Repair spall (including honeycombing)" },
    { id: "19.120", label: "Seal cracks" },
    { id: "19.123", label: "Strengthening (using plates, carbon fibre, etc.)" },
    { id: "19.352", label: "Drill drainage holes" },
    { id: "19.553", label: "Corrosion protection to steel cables" },
    { id: "19.653", label: "Access-using scaffold (> 10 m)" },
    { id: "19.654", label: "Access-using scaffold (< 10 m)" },
    { id: "19.702", label: "Traffic accommodation-Low (< 10 000 vpd)" },
    { id: "19.703", label: "Traffic accommodation-Medium (10 000 - 40 000 vpd)" },
    { id: "19.704", label: "Traffic accommodation-High (> 40 000 vpd)" },
    { id: "19.953", label: "Ad-hoc item (describe under Remarks)" }
  ],
  "DecksSlabs": [
    { id: "20.101", label: "Apply protective coating" },
    { id: "20.102", label: "Apply silanes" },
    { id: "20.103", label: "Clean concrete surface" },
    { id: "20.104", label: "Concrete (reinforced)" },
    { id: "20.108", label: "Cut back reinforcement (tie rods) and make good" },
    { id: "20.110", label: "Jacking - complicated (provide jack support work)" },
    { id: "20.111", label: "Jacking - simple (flat jacks)" },
    { id: "20.118", label: "Repair spall (including honeycombing)" },
    { id: "20.120", label: "Seal cracks" },
    { id: "20.123", label: "Strengthening (using plates, carbon fibre, etc.)" },
    { id: "20.125", label: "Waterproofing of top surface" },
    { id: "20.352", label: "Drill drainage holes" },
    { id: "20.551", label: "Paint steelwork" },
    { id: "20.553", label: "Corrosion protection to steel cables" },
    { id: "20.556", label: "Structural steel - remove all rivets and replace with bolts" },
    { id: "20.557", label: "Structural steel - remove all rivets and replace" },
    { id: "20.558", label: "Structural steel - replace bolts, washers etc." },
    { id: "20.559", label: "Replace structural steel member" },
    { id: "20.577", label: "Structural steel - sand blast to white metal" },
    { id: "20.578", label: "Strengthen structural steel member" },
    { id: "20.653", label: "Access-using scaffold (> 10 m)" },
    { id: "20.654", label: "Access-using scaffold (< 10 m)" },
    { id: "20.702", label: "Traffic accommodation-Low (< 10 000 vpd)" },
    { id: "20.703", label: "Traffic accommodation-Medium (10 000 - 40 000 vpd)" },
    { id: "20.704", label: "Traffic accommodation-High (> 40 000 vpd)" },
    { id: "20.953", label: "Ad-hoc item (describe under Remarks)" }
  ],
  "MiscellaneousItems": [
    { id: "21.119", label: "Repair support plinths" },
    { id: "21.554", label: "Corrosion protection to masts" },
    { id: "21.570", label: "Replace cover plates on street lights" },
    { id: "21.601", label: "Bolts (miscellaneous)" },
    { id: "21.604", label: "Install clearance sign" },
    { id: "21.606", label: "Install fencing" },
    { id: "21.610", label: "Rebuild/repair access chamber" },
    { id: "21.612", label: "Remove people using structure as habitat" },
    { id: "21.613", label: "Repair service hangers (lighting etc.)" },
    { id: "21.615", label: "Repair sign gantries" },
    { id: "21.616", label: "Repair signpost connections" },
    { id: "21.617", label: "Replace road signs" },
    { id: "21.619", label: "Service structure lights" },
    { id: "21.620", label: "Install structure number plate" },
    { id: "21.953", label: "Ad-hoc item (describe under Remarks)" }
  ]
}; 